### ISSUE TITLE
Add three-dimensional co-ordinate system

### ISSUE THREAD

**Issue by marc1701** [acoustics-code-salford/uas-sound-event#17]
At present, flight paths are specified solely in terms of x and z distances e.g. along a vertical slice about the receiver position. Consequently flyovers all pass directly overhead - this is fine for calculating doppler but not ideal when considering ground reflection or especially panning in 3D. 

### Task
Add y-dimension to flight path spec to enable flyovers not passing directly overhead.

**Comment by marc1701** [comment]
I have added a new system for calculating x, y, z co-ordinates at each time step based on acceleration integration equations. This has also concurrently solved issue #9.

A few further steps:

- [ ] Test integration of acceleration calculation to current code (using x/z only)
- [ ] Refactor PropagationPath object to account for y-axis
- [ ] Write unit tests for _xyz_over_time to make sure final coordinates are very near to specified end position
- [ ] Unit test for sensible results e.g. slower speeds result in longer journeys

**Comment by marc1701** [comment]
- [ ] Move phi_per_frame to __init__ of PropagationPath and add a theta_per_frame calculation (these will be needed for the Ambisonic spatialisation).
